name: Release Please

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write
  issues: write        # Added: needed for label management

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  publish:
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.release_created }}
    environment:
      name: release
      url: https://alephalpha.jfrog.io/artifactory/webapp/#/artifacts/browse/tree/General/pharia-telemetry
    permissions:
      contents: read
      id-token: write
    env:
      ARTIFACTORY_URL: https://alephalpha.jfrog.io
      ARTIFACTORY_PYPI_REPOSITORY: "pharia-telemetry"
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Build and publish to JFrog Artifactory repository
        run: |
          uv build
          echo "Getting JFrog access token..."
          export UV_PUBLISH_PASSWORD=$(.github/composites/get_jfrog_access_token.sh)
          echo "Access token length: ${#UV_PUBLISH_PASSWORD}"
          if [ -z "$UV_PUBLISH_PASSWORD" ]; then
            echo "ERROR: Failed to get JFrog access token"
            exit 1
          fi
          echo "Getting JFrog username..."
          export UV_PUBLISH_USERNAME=$(.github/composites/get_jfrog_access_token_subject.sh $UV_PUBLISH_PASSWORD)
          echo "Username: $UV_PUBLISH_USERNAME"
          if [ -z "$UV_PUBLISH_USERNAME" ]; then
            echo "ERROR: Failed to get JFrog username"
            exit 1
          fi
          echo "Publishing to Artifactory..."
          uv publish --publish-url $ARTIFACTORY_URL/artifactory/api/pypi/$ARTIFACTORY_PYPI_REPOSITORY/
